/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: hdulogo                                               *
* Dimensions:  50 * 49                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmhdulogo;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorshdulogo[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palhdulogo = {
  2,  // Number of entries
  1,  // Has transparency
  (const LCD_COLOR *)&_Colorshdulogo[0]
};

static GUI_CONST_STORAGE unsigned char _achdulogo[] = {
  ________, ________, ______XX, XXXX____, ________, ________, ________,
  ________, ________, __XXXXXX, XXXXXXXX, ________, ________, ________,
  ________, ________, XXX_____, _______X, XXX_____, ________, ________,
  ________, ____XXXX, X_____X_, ________, __XXXX__, ________, ________,
  ________, ___XX___, _______X, ____X___, _____XXX, ________, ________,
  ________, _XXX____, XX____XX, ___XXX__, _______X, X_______, ________,
  ________, _X______, X_X____X, ___X_X__, _X_X____, XX______, ________,
  ________, XX___X__, _XX_____, _____X__, _XX_____, _X______, ________,
  _______X, X_____X_, ___X____, ________, __X_____, _XX_____, ________,
  _____XXX, ____XX_X, __XX_XX_, ___XX_XX, __X___XX, __XXX___, ________,
  _____X__, ___XX___, XX______, ________, XX___X__, ____XX__, ________,
  ____XX__, ________, X_______, ________, _XX_____, _____X__, ________,
  ___XX___, _______X, X_______, ________, __XX____, _____XX_, ________,
  ___X___X, _XX___XX, ________, ________, ___XX___, ______X_, ________,
  ___X____, X____XX_, ________, ___XX___, ____XX__, ____X_XX, ________,
  ___X___X, XX_XXX__, _____X__, __XXX___, _XX__XX_, _X_X___X, ________,
  ___X____, ___X____, _____XX_, __XXXX__, XXX___XX, _X_____X, ________,
  ________, __XX____, _____XXX, __XXXX__, XXX____X, _______X, ________,
  __X___X_, __X_____, ____XXXX, X__XXXX_, XXX____X, X___X__X, ________,
  __X_____, _XX_____, ____XXXX, XX__XXX_, XXX_____, X_______, X_______,
  __X_____, _X______, _____XXX, XXX_XXX_, XXX_____, X_______, X_______,
  __X_X___, _X______, _______X, XXXXXXX_, XXX_____, XX_XX___, X_______,
  _X___X__, _X______, ___XX___, _XXXXXX_, XXX_____, XX______, X_______,
  _X______, _X______, XXX_____, _XXXXXX_, XXX_____, _X______, X_______,
  _X__X___, _X______, X_______, _XXXXX_X, XX______, _X_X____, X_______,
  _X____X_, _X_____X, X_______, __XXXX_X, XX______, _X______, X_______,
  _X______, _X____XX, X_______, __X_X_XX, X_______, _X______, X_______,
  _X____X_, _X____XX, X_______, __X_XXXX, ________, XX_X____, X_______,
  __X_XX__, _X___XXX, X_______, _X_XXX__, ________, X___XX__, X_______,
  __X_____, _XX__XXX, X_______, XX_X____, ________, X_______, X_______,
  __X__X_X, __X__XXX, X_______, ________, ____X__X, X______X, ________,
  __X_____, __XX__XX, XX______, ________, __XX___X, __X____X, ________,
  ___X_XX_, ___X__XX, XXX_____, ________, __X___XX, ___X___X, ________,
  ___X____, ___XX__X, XXXXX___, _______X, XX___XX_, _______X, ________,
  ___X__X_, _X__XXX_, XXXXXXXX, XXXXXXXX, ____XX__, _X_X__XX, ________,
  ___X____, _X____XX, ____XXXX, XXX_____, ___XX___, __X___X_, ________,
  ___XX___, __X____X, X_______, ________, __XX____, _____XX_, ________,
  ____XX__, _X______, X_______, ________, _XX_____, _X___X__, ________,
  _____X__, __X_X___, XX______, ________, XX____X_, ____XX__, ________,
  _____XX_, ____X___, __XX____, ______XX, _____X__, ___XX___, ________,
  ______XX, X_XX____, _____XX_, ____X___, __XX__X_, _XXX____, ________,
  ________, XX__X___, _X______, ________, ________, _X______, ________,
  ________, _X______, ________, ______X_, __XX____, XX______, ________,
  ________, _XX_____, X_____X_, _X__X___, __X____X, X_______, ________,
  ________, ___XX___, ____X___, _______X, _____XXX, ________, ________,
  ________, ____XXX_, ________, __X_X___, ____XX__, ________, ________,
  ________, ______XX, XXX_____, ________, XXXXX___, ________, ________,
  ________, ________, __XXXXXX, __XXXXXX, X_______, ________, ________,
  ________, ________, ______XX, XXXXX___, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmhdulogo = {
  50, // xSize
  49, // ySize
  7, // BytesPerLine
  1, // BitsPerPixel
  _achdulogo,  // Pointer to picture data (indices)
  &_Palhdulogo   // Pointer to palette
};

/*************************** End of file ****************************/
